import numpy as np
import pymesh
import vtk
import glob
import os
import logging
logging.basicConfig(level=logging.INFO)

"""
  © Aix Marseille University - LIS-CNRS UMR 7020
  Author(s): Karim Makki, Amine Bohi (karim.makki, amine.bohi{@univ-amu.fr})
  This software is governed by the CeCILL-B license under French law and
  abiding by the rules of distribution of free software.  You can  use,
  modify and/ or redistribute the software under the terms of the CeCILL-B
  license as circulated by CEA, CNRS and INRIA at the following URL
  "http://www.cecill.info".
  As a counterpart to the access to the source code and  rights to copy,
  modify and redistribute granted by the license, users are provided only
  with a limited warranty  and the software's author,  the holder of the
  economic rights,  and the successive licensors  have only  limited
  liability.
  In this respect, the user's attention is drawn to the risks associated
  with loading,  using,  modifying and/or developing or reproducing the
  software by the user in light of its specific status of free software,
  that may mean  that it is complicated to manipulate,  and  that  also
  therefore means  that it is reserved for developers  and  experienced
  professionals having in-depth computer knowledge. Users are therefore
  encouraged to load and test the software's suitability as regards their
  requirements in conditions enabling the security of their systems and/or
  data to be ensured and,  more generally, to use and operate it in the
  same conditions as regards security.
  The fact that you are presently reading this means that you have had
  knowledge of the CeCILL-B license and that you accept its terms.
"""


def initTxt(filename):
    try:
        os.remove(filename)
    except:
        pass

def save_vertices_as_vtk_file(surface_points, vtk_out):

    nbSurfacePts = len(surface_points[:,0])
    logging.info(surface_points)
    logging.info(nbSurfacePts)
    initTxt(vtk_out)
    vtk_file = open(vtk_out, "a")
    vtk_file.write("# vtk DataFile Version 3.0\n")
    vtk_file.write("vtk output\n")
    vtk_file.write("ASCII\n")
    vtk_file.write("DATASET POLYDATA\n")
    vtk_file.write("POINTS {} float\n".format(nbSurfacePts))
    for c in range(nbSurfacePts):
        vtk_file.write("{:.1f} {:.1f} {:.1f}\n".format(surface_points[c,0], surface_points[c,1], surface_points[c,2]))
    print(c)
    vtk_file.write("VERTICES {} {}\n".format(nbSurfacePts, nbSurfacePts*2))
    for c in range(nbSurfacePts):
        vtk_file.write("1 {}\n".format(c))


# The current folder should contain all the quad meshes generated by Instant Meshes
# This will output a set of vtk files containing the mesh vertices or the point to be tracked

subjectSet = glob.glob('./*.obj') 

subjectSet.sort()
print(subjectSet)

for subject in range(len(subjectSet)):
 
        
        subject_name = subjectSet[subject].split('/')[-1].split('.')[0]
 
        outfile_name = './'+subject_name+'.vtk'

        m = pymesh.load_mesh(subjectSet[subject])

        print(m.vertices.shape)

        save_vertices_as_vtk_file(m.vertices, outfile_name)



        

